name: Build and Publish .NET Framework 4.8 MVC Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # This should be your self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NuGet Path
        run: echo "C:\Tools" >> $GITHUB_PATH

      - name: Restore NuGet packages
        run: |
          & "C:\Tools\nuget.exe" restore HSR.sln

      - name: Setup MSBuild Path
        run: echo "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin" >> $GITHUB_PATH

      - name: Build project
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\msbuild.exe" HSR.sln /p:Configuration=Release /p:RestorePackagesConfig=true

      - name: Publish project
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\msbuild.exe" HSR.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishUrl="C:\PublishedFiles"

      - name: Copy published files
        run: |
          Copy-Item -Path "C:\PublishedFiles" -Destination "C:\AnotherDestination" -Recurse -Force
        shell: pwsh  # You can use pwsh or powershell as per your preference
