name: Build and Publish .NET Framework 4.8 MVC Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # This should be your self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NuGet Path
        run: echo "C:\Tools" >> $GITHUB_PATH

      - name: Restore NuGet packages
        run: |
          & "C:\Tools\nuget.exe" restore HSR.sln

      - name: Setup MSBuild Path
        run: echo "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin" >> $GITHUB_PATH

      - name: Build project
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\msbuild.exe" HSR.sln /p:Configuration=Release

      - name: Publish project
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\msbuild.exe" HSR.csproj /p:Configuration=Release /p:OutputPath=./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: publish-output
          path: ./publish

      - name: Copy build output to network drive
        run: |
          $destination = 'E:\Project\dev-hsr.kipp\new\hsr-2.0'
          New-Item -ItemType Directory -Force -Path $destination
          Copy-Item -Path ./publish/* -Destination $destination -Recurse -Force
        shell: pwsh
